config/routes.rb
YelpEsque::Application.routes.draw do
  devise_for :users

  root 'places#index'

  resources :places do
    resources :comments, :only => :create
    resources :photos
  end

  resources :users, :only => :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
    '★☆☆☆☆' => '1_star',
    '★★☆☆☆' => '2_stars',
    '★★★☆☆' => '3_stars',
    '★★★★☆' => '4_stars',
    '★★★★★' => '5_stars',
  }

  def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
    NotificationMailer.comment_added(self).deliver
  end

  validates :rating, :presence => true
  validates :message, :presence => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :place

  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    new_record? || slug.nil? || slug.blank? # you can add more condition here
  end

  belongs_to :user
  has_many :comments
  has_many :photos

  geocoded_by :address
  after_validation :geocode

  validates :name, :presence => true
  validates :description, :presence => true
  validates :address, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_many :places
  has_many :comments

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

  validates :username, :presence => true, :uniqueness => {:case_sensitive => false}

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.comments.create(comment_params.merge(:user => current_user))
    redirect_to place_path(@place)
  end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  def create
    @place = Place.find(params[:place_id])
    @place.photos.create(photo_params)
    redirect_to place_path(@place)
  end

  private

  def photo_params
    params.require(:photo).permit(:picture, :caption)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all.order("id DESC").page(params[:page]).per(4)
  end

  def new
    @place = Place.new
  end

  def edit
    @place = Place.friendly.find(params[:id])

    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end
  end

  def show
    @place = Place.friendly.find_by(slug: params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def update
    @place = Place.friendly.find.(params[:id])
    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end
    @place.update_attributes(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to place_path(@place)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def destroy
    @place = Place.friendly.find.(params[:id])
    if @place.user != current_user
      return render :text => 'Not Allowed', :status => :forbidden
    end
    @place.destroy
    redirect_to root_path
  end

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>YelpEsque</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a><%= link_to 'Yelpesque!', root_path, :class => "navbar-brand" %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to new_place_path do %>
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            Add Place
          <% end %>
          </li>
        </ul>
          
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
            </li>
          <% else %>
            <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <% if notice.present? %>
    <div class="alert alert-info col-xs-8 col-xs-offset-2" role="alert"><%= notice %></div>
  <% end %>
  <% if alert.present? %>
    <div class="alert alert-warning col-xs-8 col-xs-offset-2"><%= alert %></div>
  <% end %>
  <br class="clear"/>
  <%= yield %>

</body>
</html>

app/views/places/edit.html.erb
<div class="card-tallbox col-xs-10 col-xs-offset-1">
  <h2>Update Details for this Place</h2>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Update', :class => 'btn btn-success' %>
    <br class="clear" />
    <br />
    <hr class="clear" />
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Delete Place', place_path(@place), :method => :delete, :data => {:confirm => 'Are you sure to delete this place?'}, :class => 'btn btn-danger pull-right' %>
    <% end %>
    <br class="clear" />
    <br />
  <% end %>
</dvi>

app/views/places/index.html.erb
<!-- Carousel -->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'slider1.JPG', :class => "img-responsive" %>
      <div class="carousel-caption">
        Feeling Italian?
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slider2.JPG' %>
      <div class="carousel-caption">
        Feeling Christmasy?
      </div>
    </div>
    <div class="item">
      <%= image_tag 'slider3.JPG' %>
      <div class="carousel-caption">
        Feel Like Fusions?
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="pull-right"><%= paginate @places %></div>
<br class="clear"/>

<div class="container">
  <div class="row">
    <% @places.each do |place| %>
      <div class="col-xs-12 col-sm-6">
        <div class="card-tallbox col-xs-12">
          <h3><%= link_to place.name, place_path(place) %></h3>
          <i><p><%= place.address %></p></i>
          <p><%= place.description %></p>
          
          <% if place.photos.present? %>
              <%= link_to image_tag(place.photos.order("id DESC").last.picture, :class => "img-responsive img"), place_path(place)%>
          <% end %>
          <br />

          <% if place.comments.present? %>
            <div class="col-xs-12">
              <blockquote>
                <%= place.comments.order("id ASC").last.message %>
                <br />
                <% if place.comments.order("id ASC").last.humanized_rating.present? %>
                  <b id="star"><%= place.comments.order("id ASC").last.humanized_rating %></b>
                <% end %>
                <small><%= place.comments.order("id ASC").last.user.username %></small>
              </blockquote>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br class="clear"/>
<div class="pull-right"><%= paginate @places %></div>

app/views/places/new.html.erb
<div class="card-tallbox col-xs-10 col-xs-offset-1">
  <h1>Add a New Place Here</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name, :label => 'Restaurant Name', :placeholder => 'Champagne Bar' %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Submit', :class => 'btn btn-success' %>
    <br class="clear"/>
    <br />
    <br />
    <br />
  <% end %>
</dvi>

app/views/places/show.html.erb
<div class="card-tallbox col-xs-10 col-xs-offset-1">
  <h1 class="pull-left"><strong><%= @place.name %></strong></h1>
  <br />
  <div class="pull-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to "Edit Place Details", edit_place_path(@place), :class => 'btn btn-info' %>
    <% end %>
    <% if current_user %>
      <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal_Photo">
        Add Photos
      </button>
    <br class="clear"/>
    <br />
    <% end %>
  </div>
  <br class="clear"/>

  <i><h4><%= "Address: #{@place.address}" %></h4></i>
  <h4><%= "Description: #{@place.description}" %></h4>
  <% if @place.user.present? %>
    <small class="pull-right"><%= "Added by #{@place.user.username}" %></small>
  <% end %>
  <br class="clear"/>
  <br />

<!-- Button trigger modal for Photos-->
  

  <% @place.photos.order("id ASC").each do |photo| %>
    <div class="col-xs-12 col-sm-4">
        <%= image_tag(photo.picture, :class => "img-responsive img") %>
        <h6 style="text-align: center"><%= photo.caption %></h6>
    </div>
  <% end %>
  <br class="clear" />
  <br />

  <!-- Modal for Photos-->
  <div class="modal fade" id="myModal_Photo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add Photos</h4>
        </div>

        <%= simple_form_for @photo, :url => place_photos_path(@place) do |f| %>
          <div class="modal-body">
              <div class="clear">
                <%= f.input :picture %>
                <br />
                <%= f.input :caption, :label => 'Caption' %>
              </div>
              <br class="clear"/>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Add Photos", :class => 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Google Map -->
  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>
      function initMap() {
        var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }
    </script>
    
    <script async defer
      src="https://maps.googleapis.com/maps/api/js?signed_in=true&callback=initMap"></script>

    <div id="map"></div>
  <% end %>
  <br />
  <hr />

  <!-- Modal for Comment-->
  <div class="modal fade" id="myModal_Comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Add a Comment</h4>
        </div>

        <%= simple_form_for @comment, :url => place_comments_path(@place) do |f| %>
          <div class="modal-body">
              <div class="clear">
                <%= f.input :message, :label => 'Comment' %>
                <br />
                <%= f.input :rating, :as => :select, :collection => Comment::RATINGS %>
              </div>
              <br class="clear"/>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Add a Comment", :class => 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <h2 class="pull-left">Comments</h2>
  <!-- Button trigger modal for Comment-->
  <% if current_user %>
  <br />
    <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal_Comment">
      Add a Comment
    </button>
  <% end %>
  <br class="clear" />
  <% @place.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-6">
      <blockquote>
        <%= comment.message %>
        <br />
        <% if comment.humanized_rating.present? %>
          <b id="star"><%= comment.humanized_rating %></b>
        <% end %>
        <small><%= comment.user.username %></small>
      </blockquote>
    </div>
  <% end %>
  <br />
  <br />
</div>

app/views/users/show.html.erb
<div class="card-tallbox col-xs-10 col-xs-offset-1">
  <br class="clear" />
  <div class="col-xs-8">
    <h1><%= @user.username %></h1>
    <h4>Email: <%= @user.email %></h4>
    <h4>Member Since: <%= @user.created_at.strftime("%d %B, %Y") %></h4>
    <br class="clear" />

    <h4><%= @user.comments.count %> total comments</h4>
    <h4><%= @user.comments.where(:rating => '5_stars').count %> total 5-stars reviews</h4>
  </div>

  <div class="col-xs-4 hidden-xs pull-right">
    <%= image_tag 'userprofile.png', :style => "margin: 20px 20px 20% 20%" %>
  </div>
  <br class="clear" />
  <hr />

  <h2 class="text-center">My Places</h2>
    <% @user.places.each do |place| %>
    <h3><%= link_to place.name, place_path(place) %></h3>
    <i><p><%= place.address %></p></i>
    <p><%= place.description %></p>

      <% if place.photos.present? %>
        <%= link_to image_tag(place.photos.order("id DESC").last.picture, :class => "img-responsive"), place_path(place)%>
        <br />
      <% end %>
    <% end %>
  <hr />

  <h2 class="text-center">My Comments</h2>
  <% @user.comments.each do |comment| %>
    <blockquote>
      <%= comment.message %>
      <br />
      <% if comment.humanized_rating.present? %>
        <b id="star"><%= comment.humanized_rating %></b>
        <br />
      <% end %>
      <b>@ <%= link_to comment.place.name, place_path(comment.place) %></b>
    </blockquote>
  <% end %>


</div>